name: Label PRs

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: anencore94/labeler@v1.0.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

# TODO
# 커밋 로그 정리
# README 정리